targets:
  $default:
    builders:
      graphql_codegen:
        options:
          assetsPath: lib/core/graphql/**
          outputDirectory: __generated
          clients:
            - graphql
          enums:
            ConditionEnum:
              type: ConditionsEnum
              fromJsonFunctionName: ConditionsEnum.conditionByApiValue
              toJsonFunctionName: ConditionsEnum.conditionToApiValue
              import: package:prelura_app/modules/model/product/product_model.dart
          scalars:
            ExpectedErrorType:
              type: Map<String, dynamic>
            Date:
              type: DateTime
            DateTime:
              type: DateTime
            Decimal:
              type: String
            JSONString:
              type: String
            GenericScalar:
              type: dynamic
