targets:
  $default:
    builders:
      graphql_codegen:
        options:
          assetsPath: lib/core/graphql/**
          outputDirectory: __generated
          clients:
            - graphql
          scalars:
            ExpectedErrorType:
              type: Map<String, dynamic>
            Date:
              type: DateTime
            DateTime:
              type: DateTime
            Decimal:
              type: String
            JSONString:
              type: String
            GenericScalar:
              type: dynamic
