name: prelura_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  auto_route:
  sizer: ^2.0.15
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.9
  flutter_rating_bar: ^4.0.0
  visibility_detector: ^0.4.0+2
  flutter_riverpod: ^2.5.1
  image_picker: ^0.8.7+3
  flutter_native_splash: ^2.4.3
  intl: ^0.19.0
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  contentsize_tabbarview: ^0.0.2
  freezed_annotation:
  json_annotation:

  graphql:
  rxdart:
  http:
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  auto_route_generator:
  build_runner: ^2.4.7
  freezed:
  json_serializable:
  graphql_codegen:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/svgs/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

flutter_native_splash:
  color: "#ffffff" # Background color of the splash screen
  image: assets/splash_logo.png # Path to your splash image
  android: true # Enable for Android
  ios: true # Enable for iOS
  web: false # (Optional) Enable for web
  android_gravity: center # Position the image
  ios_content_mode: center
